### ISSUE TITLE
Dont start bot

### ISSUE THREAD

**Issue by JSanchezFDZ** [tlopster/channel-access-control-tg-bot#1]
Show this message on yarn start

00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'start'

**Comment by JSanchezFDZ** [comment]
npm start

> channel-access-tg-bot@1.0.0 start /home/BotVIP/channel-access-control-tg-bot
> npm run build && node ./dist/index.js


> channel-access-tg-bot@1.0.0 build /home/BotVIP/channel-access-control-tg-bot
> tsc --project ./tsconfig.json

/home/BotVIP/channel-access-control-tg-bot/node_modules/whatwg-url/lib/encoding.js:2
const utf8Encoder = new TextEncoder();
                    ^

ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/home/BotVIP/channel-access-control-tg-bot/node_modules/whatwg-url/lib/encoding.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/BotVIP/channel-access-control-tg-bot/node_modules/whatwg-url/lib/url-state-machine.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! channel-access-tg-bot@1.0.0 start: `npm run build && node ./dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the channel-access-tg-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tlopster** [comment]
> npm start
> 
> > channel-access-tg-bot@1.0.0 start /home/BotVIP/channel-access-control-tg-bot
> > npm run build && node ./dist/index.js
> 
> > channel-access-tg-bot@1.0.0 build /home/BotVIP/channel-access-control-tg-bot
> > tsc --project ./tsconfig.json
> 
> /home/BotVIP/channel-access-control-tg-bot/node_modules/whatwg-url/lib/encoding.js:2 const utf8Encoder = new TextEncoder(); ^
> 
> ReferenceError: TextEncoder is not defined at Object. (/home/BotVIP/channel-access-control-tg-bot/node_modules/whatwg-url/lib/encoding.js:2:21) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object. (/home/BotVIP/channel-access-control-tg-bot/node_modules/whatwg-url/lib/url-state-machine.js:5:34) at Module._compile (internal/modules/cjs/loader.js:778:30) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! channel-access-tg-bot@1.0.0 start: `npm run build && node ./dist/index.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the channel-access-tg-bot@1.0.0 start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Use yarn

**Comment by tlopster** [comment]
`npm i yarn --global`
`yarn install`
`yarn start`
